name: micro_services_pipeline

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: install dependencies for python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install pytest
        run: pip install pytest

      - name: install dependencies for node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install and test node
        working-directory: ./service_b
        run: |
          npm install
          npm test

  build-service-a:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::157542114056:role/github-actions-micro-services-role
          aws-region: eu-west-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push service-a
        run: |
          docker build -t 157542114056.dkr.ecr.eu-west-1.amazonaws.com/service-a:latest ./service_a
          docker push 157542114056.dkr.ecr.eu-west-1.amazonaws.com/service-a:latest

  build-service-b:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::157542114056:role/github-actions-micro-services-role
          aws-region: eu-west-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push service-b
        run: |
          docker build -t 157542114056.dkr.ecr.eu-west-1.amazonaws.com/service-b:latest ./service_b
          docker push 157542114056.dkr.ecr.eu-west-1.amazonaws.com/service-b:latest
